[project]
name = "sih"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp==3.13.2",
    "alembic==1.15.2",
    "bcrypt==4.3.0",
    "beautifulsoup4>=4.14.3",
    "click==8.1.8",
    "colorama==0.4.6",
    "cryptography==44.0.2",
    "dnspython==2.8.0",
    "duckduckgo-search==7.5.5",
    "easyocr==1.7.2",
    "email-validator==2.2.0",
    "faiss-cpu==1.9.0",
    "fastapi==0.115.12",
    "ffmpeg-python==0.2.0",
    "google-cloud-speech==2.26.0",
    "google-generativeai==0.8.3",
    "gotrue==2.12.4",
    "h11==0.14.0",
    "h2==4.3.0",
    "httpcore==1.0.7",
    "httptools==0.6.4",
    "httpx==0.28.1",
    "huggingface-hub==0.36.0",
    "jinja2==3.1.6",
    "langchain==0.3.18",
    "langchain-anthropic==0.3.8",
    "langchain-community==0.3.17",
    "langchain-core==0.3.39",
    "langchain-google-genai==2.0.8",
    "langchain-huggingface==0.1.2",
    "langchain-text-splitters==0.3.6",
    "langchainhub==0.1.21",
    "langgraph==0.2.66",
    "langsmith>=0.3.45",
    "lxml==6.0.2",
    "mako==1.3.9",
    "markdown-it-py==3.0.0",
    "ninja==1.13.0",
    "numpy>=1.26.4,<2.0.0",
    "openai-whisper==20231117",
    "opencv-python-headless==4.10.0.84",
    "orjson==3.10.16",
    "pandas>=2.3.3",
    "passlib==1.7.4",
    "pgvector==0.3.6",
    "pillow==11.1.0",
    "postgrest==0.19.3",
    "psycopg2-binary==2.9.10",
    "pyclipper==1.3.0.post6",
    "pydantic==2.9.2",
    "pydantic-core==2.23.4",
    "pydantic-extra-types==2.10.3",
    "pydantic-settings==2.6.0",
    "pygments==2.19.1",
    "pyjwt==2.10.1",
    "pymupdf==1.25.2",
    "pytest==9.0.1",
    "pytest-mock==3.15.1",
    "python-bidi==0.6.7",
    "python-dateutil==2.9.0.post0",
    "python-docx==1.1.2",
    "python-dotenv==1.1.0",
    "python-jose==3.4.0",
    "python-multipart==0.0.20",
    "python-pptx==1.0.2",
    "pyyaml==6.0.2",
    "rank-bm25==0.2.2",
    "realtime==2.0.0",
    "requests>=2.32.5",
    "rich==13.9.4",
    "schedule==1.2.2",
    "scikit-image==0.25.2",
    "scikit-learn==1.7.2",
    "scipy==1.16.3",
    "sentence-transformers==3.3.1",
    "shapely==2.1.2",
    "sniffio==1.3.1",
    "sqlalchemy==1.4.0",
    "starlette==0.46.1",
    "storage3==0.11.3",
    "supabase==2.11.0",
    "supafunc==0.9.4",
    "transformers==4.57.3",
    "typer==0.15.2",
    "typing-extensions==4.12.2",
    "ujson==5.10.0",
    "uvicorn==0.34.0",
    "watchfiles==1.0.4",
    "websockets==12.0",
]
